# # Definitions of tags to detect
#
# ## General remarks
#
# - All length in meters
# - 'size' refers to the length of the shared border between solid black and solid white rectangle.
#   See README.md or https://github.com/AprilRobotics/apriltag/wiki/AprilTag-User-Guide#pose-estimation for details.
# - Ellipsis (...) signifies that the previous element can be repeated multiple times.
#
# ## Standalone tag definitions
# ### Remarks
#
# - name is optional
#
# ### Syntax
#
# standalone_tags:
#   [
#     {id: ID, size: SIZE, name: NAME},
#     ...
#   ]
standalone_tags:
  [
    { id: 2, size: 0.08, name: "april_tag2" },
    { id: 1, size: 0.08, name: "april_tag1" },
    { id: 0, size: 0.08, name: "april_tag0" },
    { id: 3, size: 0.08, name: "april_tag3" },
  ]
# ## Tag bundle definitions
# ### Remarks
#
# - name is optional
# - x, y, z have default values of 0 thus they are optional
# - qw has default value of 1 and qx, qy, qz have default values of 0 thus they are optional
#
# ### Syntax
#
# tag_bundles:
#   [
#     {
#       name: 'CUSTOM_BUNDLE_NAME',
#       layout:
#         [
#           {id: ID, size: SIZE, x: X_POS, y: Y_POS, z: Z_POS, qw: QUAT_W_VAL, qx: QUAT_X_VAL, qy: QUAT_Y_VAL, qz: QUAT_Z_VAL},
#           ...
#         ]
#     },
#     ...
#   ]
tag_bundles:
  [
    {
      name: 'bundle5',
      layout:
        [
          { id: 0, size: 0.08, x: 0, y: 0, z: 0, qw: 1, qx: 0, qy: 0, qz: 0 },
          { id: 2, size: 0.08, x: -0.09, y: 0, z: 0, qw: 1, qx: 0, qy: 0, qz: 0 },
          { id: 3, size: 0.08, x: 0.09, y: 0, z: 0, qw: 1, qx: 0, qy: 0, qz: 0 }
        ]
    },
    {
      name: 'bundle0',
      layout:
        [
          { id: 1, size: 0.04, x: 0, y: 0, z: 0, qw: 1, qx: 0, qy: 0, qz: 0 },
          { id: 0, size: 0.04, x: -0.048, y: 0, z: 0, qw: 1, qx: 0, qy: 0, qz: 0 },
          { id: 2, size: 0.04, x: 0.048, y: 0, z: 0, qw: 1, qx: 0, qy: 0, qz: 0 }
        ]
    },
    {
      name: 'bundle1',
      layout:
        [
          { id: 1, size: 0.08, x: 0, y: 0, z: 0, qw: 1, qx: 0, qy: 0, qz: 0 },
          { id: 0, size: 0.08, x: -0.09, y: 0, z: 0, qw: 1, qx: 0, qy: 0, qz: 0 },
          { id: 2, size: 0.08, x: 0.09, y: 0, z: 0, qw: 1, qx: 0, qy: 0, qz: 0 }
        ]
    }

  ]
